/* Transformation Name ==>SC_RR_RATE_MARKET_MARGIN_FACT ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='RR_RATE_MARKET_MARGIN_FACT',
		schema='EMIR_SHARED',
		pre_hook ="",
		post_hook ="",
		incremental_strategy='append')
}}

With BATCH_DETAILSOut as (
	/* transType: "LookupSource" */
Select ID, 
		BATCH_ID, 
		TARGET_TABLE_NAME, 
		FILE_NAME, 
		STATUS, 
		in_BATCH_ID, 
		in_TARGET_TABLE_NAME, 
		in_SOURCE_NAME
 from 
{{ source ('SC_LKP_BATCH_DETAILS_ID_1','BATCH_DETAILS') }}
 ),

ENTITY_DIMOut as (
	/* transType: "LookupSource" */
Select DIMENSION_KEY, 
		NAME, 
		EFFECTIVE_DATE, 
		EXPIRATION_DATE, 
		i_NAME, 
		i_DATE
 from 
{{ source ('SC_LKP_ENTITY_DIM_1','ENTITY_DIM') }}
 ),

CALENDAR_DIMOut as (
	/* transType: "LookupSource" */
Select ID, 
		NAME, 
		DESCRIPTION, 
		TYPE, 
		CAL_DATE, 
		DAY_NAME, 
		WEEK_NUMBER, 
		MONTH_NUMBER, 
		MONTH_NAME, 
		QUARTER, 
		YEAR, 
		YEAR_MONTH, 
		YEAR_QUARTER, 
		WEEKEND_IND, 
		LCH_WORKING_DAY_IND, 
		LCH_HOLIDAY_IND, 
		EXTERNAL_WORKING_DAY_IND, 
		EXTERNAL_HOLIDAY_IND, 
		i_CAL_TYPE, 
		i_DATE
 from 
{{ source ('SC_LKP_CALENDAR_DIM_IRM_1','CALENDAR_DIM') }}
 ),

SQ_SC_IRM_MARGINS_YYYYMMDD_EODOut as (
	/* transType: "Source" */
Select BUSINESS_DATE, 
		DAY_PERIOD_TYPE_INDICATOR, 
		GRI_RUN_ID, 
		MARGIN_GROUP, 
		MARKET_ID, 
		MEMBER_MNEMONIC, 
		TRADER_MNEMONIC, 
		MARGIN_ACCOUNT_TYPE, 
		CURRENCY, 
		IM_TOTAL, 
		IM_OPEN, 
		IM_DELIVERY, 
		VM, 
		CVM, 
		NLV, 
		ESA, 
		CRIM, 
		IMM, 
		DFAM, 
		PARTICIPANT_ROLE_TYPE, 
		POSITION_ACCOUNT_TYPE, 
		CLIENT_IDENTIFIER, 
		CLIENT_IDENTIFIER_TYPE, 
		IMM1, 
		OUTRIGHT_RATES_IMMFP, 
		BASIS_IMMFP, 
		OPTIONS_LIQUIDITY_MARGIN, 
		LCRM, 
		OPTIONS_VOLATILITY_ADJUSTMENT, 
		UNSCALED_VAR_ADDON, 
		NET_BH_TOTAL, 
		CCY_HOL_VM, 
		OPTION_PREMIUM, 
		FXAddOn, 
		MER, 
		SPMAddon
 from 
{{ source ('FlatFile_catalog_1','IRM_MARGINS_YYYYMMDD_EOD') }} 
 ),

COUNTERPARTIES_DIMOut as (
	/* transType: "LookupSource" */
Select ID, 
		BATCH_ID, 
		BATCH_START_DATE, 
		CLEARING_MEMBER_MNEMONIC, 
		EXCHANGE_MNEMONIC, 
		CLEARING_SYSTEM_CLIENT_ID, 
		COUNTERPARTY_NAME, 
		LEGAL_ENTITY_IDENTIFIER, 
		BIC_CODE, 
		LCH_UNIQUE_ID, 
		CFTC_INTERIM_COMPLIANT_ID, 
		ADDRESS_LINE_1, 
		ADDRESS_LINE_2, 
		ADDRESS_LINE_3, 
		ADDRESS_LINE_4, 
		ADDRESS_LINE_5, 
		POSTCODE, 
		DATE_OF_INCORPORATION, 
		INCORPORATION_COUNTRY_NAME, 
		INCORPORATION_COUNTRY_CODE, 
		INCORPORATION_IN_EU_IND, 
		DOMICILE_COUNTRY_NAME, 
		DOMICILE_COUNTRY_CODE, 
		DOMICILE_IN_EU_IND, 
		CATEGORY, 
		FINANCIAL_CATEGORY, 
		POSITION_ACCOUNT_REF, 
		MARGIN_ACCOUNT_REF, 
		MARGIN_AGGREGATED_ACCOUNT_REF, 
		ACCOUNT_TYPE, 
		CONTACT_NAME, 
		CONTACT_EMAIL1, 
		CONTACT_EMAIL2, 
		CONTACT_PHONE1, 
		CONTACT_PHONE2, 
		EFFECTIVE_FROM_DATE, 
		EFFECTIVE_TO_DATE, 
		i_EXCHANGE_MNEMONIC, 
		i_LCH_UNIQUE_ID, 
		i_CLEARING_MEMBER_MNEMONIC, 
		i_DATE
 from 
{{ source ('SC_LKP_COUNTERPARTIES_DIM_MBR_CPTY_ID_1','COUNTERPARTIES_DIM') }}
 ),

Target_Table_Name_SK_Max_Value AS (
  SELECT
    MAX(GENERATED_SEQ) AS max_generated_seq
  FROM {{ this }}
),

 DSR_EXP_EPOC_FORMATOut as (
	/* transType: "Expression" */
Select 
	SC_SEQ_RR_RATE_MARKET_MARGIN_FACTOut.(SELECT max_generated_seq FROM Target_Table_Name_SK_Max_Value) + ROW_NUMBER() OVER() AS GENERATED_SEQ
From SC_SEQ_RR_RATE_MARKET_MARGIN_FACTOut as SC_SEQ_RR_RATE_MARKET_MARGIN_FACTOut),

exp_Populate_TargetOut as (
	/* transType: "Expression" */
Select 
	UPPER ( LTRIM ( RTRIM ( CURRENCY ) ) ) as v_CURRENCY,
	 UPPER ( LTRIM ( RTRIM ( dsf_1.STRING_VALUE ) ) ) as v_BASE_CURRENCY,
	 TO_DATE ( LTRIM ( RTRIM ( BUSINESS_DATE ) ),
	 'YYYYMMDD' ) as v_BUSINESS_DATE,
	 DECODE ( DAY_PERIOD_TYPE_INDICATOR,
	 'I',
	 0,
	 'E',
	 ( CASE WHEN dsf_2.FX_RATE IS NULL THEN ABORT ( 'Error:Fx-Rate returned null from FX_RATE_DIM for Type:EOD,Source Currency:' || v_CURRENCY || ' Target Currency:' || v_BASE_CURRENCY || ' and Business_Date:' || TO_VARCHAR ( v_BUSINESS_DATE,
	 'YYYY-MM-DD' ) ) ELSE dsf_2.FX_RATE END ) ) as v_FXRATE,
	 '{{ var("ENTITY") }}' as o_ENTITY,
	 'LTD_STD' as o_LK_CALC_TYPE,
	 '{{ var("IRM_MARGINS_FILE_NAME") }}' as O_LK_FILE_NAME,
	 'RR_RATE_MARKET_MARGIN_FACT' as o_TARGET_TABLE,
	 '-2' as o_LK_EXCHANGE_MNEMONIC_CNTPRTY,
	 '-2' as o_LK_LCH_UNIQUE_ID,
	 UPPER ( LTRIM ( RTRIM ( MEMBER_MNEMONIC ) ) ) as o_LK_MEMBER_MNEMONIC,
	 '{{ var("BATCH_ID") }}' as o_BATCH_ID,
	 v_BUSINESS_DATE as o_BUSINESS_DATE,
	 LTRIM ( RTRIM ( UPPER ( DAY_PERIOD_TYPE_INDICATOR ) ) ) as o_DAY_PERIOD_TYPE_INDICATOR,
	 GRI_RUN_ID as o_GRI_RUN_ID,
	 LTRIM ( RTRIM ( UPPER ( MARGIN_GROUP ) ) ) as o_MARGIN_GROUP,
	 UPPER ( LTRIM ( RTRIM ( MARKET_ID ) ) ) as o_MARKET_ID,
	 LTRIM ( RTRIM ( TRADER_MNEMONIC ) ) as o_TRADER_MNEMONIC,
	 LTRIM ( RTRIM ( MARGIN_ACCOUNT_TYPE ) ) as o_ACCOUNT_TYPE,
	 ( CASE WHEN dsf_3.ID IS NULL THEN ABORT ( 'Error:ID Not found at CURRENCY_DIM for Currency:' || v_CURRENCY ) ELSE dsf_3.ID END ) as o_CURRENCY_ID,
	 ( CASE WHEN dsf_4.ID IS NULL THEN ABORT ( 'Error:ID Not found at CURRENCY_DIM for Base Currency:' || v_BASE_CURRENCY ) ELSE dsf_4.ID END ) as o_BASE_CURRENCY_ID,
	 v_FXRATE as o_FXRATE,
	 ( CASE WHEN TO_DECIMAL ( IM_TOTAL ) = 0 THEN 0 ELSE ( TO_DECIMAL ( IM_TOTAL ) * -1 ) END ) as o_IM,
	 ( CASE WHEN TO_DECIMAL ( IM_OPEN ) = 0 THEN 0 ELSE ( TO_DECIMAL ( IM_OPEN ) * -1 ) END ) as o_IM_OPEN,
	 ( CASE WHEN TO_DECIMAL ( IM_DELIVERY ) = 0 THEN 0 ELSE ( TO_DECIMAL ( IM_DELIVERY ) * -1 ) END ) as o_IM_DELIVERY,
	 VM as o_VM,
	 CVM as o_CVM,
	 NLV as o_NLV,
	 ESA as o_ESA,
	 CRIM as o_CRIM,
	 IMM as o_IMM,
	 DFAM as o_DFAM,
	 TO_DECIMAL ( IM_TOTAL,
	 10 ) * v_FXRATE * -1 as o_IM_FX,
	 TO_DECIMAL ( CRIM,
	 10 ) * v_FXRATE as o_CRIM_FX,
	 TO_DECIMAL ( IMM,
	 10 ) * v_FXRATE as o_IMM_FX,
	 LTRIM ( RTRIM ( PARTICIPANT_ROLE_TYPE ) ) as o_PARTICIPANT_ROLE_TYPE,
	 LTRIM ( RTRIM ( POSITION_ACCOUNT_TYPE ) ) as o_POSITION_ACCOUNT_TYPE,
	 LTRIM ( RTRIM ( CLIENT_IDENTIFIER ) ) as o_CLIENT_IDENTIFIER,
	 LTRIM ( RTRIM ( CLIENT_IDENTIFIER_TYPE ) ) as o_CLIENT_IDENTIFIER_TYPE,
	 IMM1 as o_IMM1,
	 OUTRIGHT_RATES_IMMFP as o_OUTRIGHT_RATES_IMMFP,
	 BASIS_IMMFP as o_BASIS_IMMFP,
	 OPTIONS_LIQUIDITY_MARGIN as o_OPTIONS_LIQUIDITY_MARGIN,
	 LCRM as o_LCRM,
	 OPTIONS_VOLATILITY_ADJUSTMENT as o_OPTIONS_VOLATILITY_ADJUSTMENT,
	 UNSCALED_VAR_ADDON as o_UNSCALED_VAR_ADDON,
	 NET_BH_TOTAL as o_NET_BH_TOTAL,
	 CCY_HOL_VM as o_CCY_HOL_VM,
	 TO_DECIMAL ( CCY_HOL_VM,
	 10 ) * v_FXRATE as o_CCY_HOL_VM_FX,
	 OPTION_PREMIUM as o_OPTION_PREMIUM,
	 FXAddOn as o_FXAddOn,
	 TO_DECIMAL ( FXAddOn,
	 10 ) * v_FXRATE as o_FXAddOn_FX,
	 1 as o_ACTIVE_FLAG,
	 v_TOT_REC_COUNT + 1 as v_TOT_REC_COUNT,
	 MER as MER,
	 TO_DECIMAL ( SPMAddon ) as o_SPMAddon 
From SQ_SC_IRM_MARGINS_YYYYMMDD_EODOut as SQ_SC_IRM_MARGINS_YYYYMMDD_EODOut 
LEFT JOIN (
SELECT STRING_VALUE, VARIABLE_NAME FROM (  SELECT STRING_VALUE, VARIABLE_NAME,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE, VARIABLE_NAME,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME ORDER BY VARIABLE_NAME NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.VARIABLE_NAME = 'RATE_MARKET_MARGIN_BASE_CURRENCY'
LEFT JOIN (
SELECT FX_RATE, TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME FROM (  SELECT FX_RATE, TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME,  ROW_NUMBER() OVER (PARTITION BY TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT FX_RATE, TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME,  ROW_NUMBER() OVER (PARTITION BY TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME ORDER BY TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    FX_RATE_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.TYPE = 'EOD' AND dsf_2.SOURCE_CURRENCY = v_CURRENCY AND dsf_2.TARGET_CURRENCY = v_BASE_CURRENCY AND dsf_2.BUSINESS_DATE_TIME = v_BUSINESS_DATE
LEFT JOIN (
SELECT ID, CURRENCY_MNEMONIC FROM (  SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY CURRENCY_MNEMONIC NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    CURRENCY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.CURRENCY_MNEMONIC = v_CURRENCY
LEFT JOIN (
SELECT ID, CURRENCY_MNEMONIC FROM (  SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY CURRENCY_MNEMONIC NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    CURRENCY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.CURRENCY_MNEMONIC = v_BASE_CURRENCY
Where MEMBER_MNEMONIC  !=  'XCH'),

exp_Populate_TargetOut1 as (
	/* transType: "Expression" */
Select 
	UPPER ( LTRIM ( RTRIM ( CURRENCY ) ) ) as v_CURRENCY,
	 UPPER ( LTRIM ( RTRIM ( dsf_1.STRING_VALUE ) ) ) as v_BASE_CURRENCY,
	 TO_DATE ( LTRIM ( RTRIM ( BUSINESS_DATE ) ),
	 'YYYYMMDD' ) as v_BUSINESS_DATE,
	 DECODE ( DAY_PERIOD_TYPE_INDICATOR,
	 'I',
	 0,
	 'E',
	 ( CASE WHEN dsf_2.FX_RATE IS NULL THEN ABORT ( 'Error:Fx-Rate returned null from FX_RATE_DIM for Type:EOD,Source Currency:' || v_CURRENCY || ' Target Currency:' || v_BASE_CURRENCY || ' and Business_Date:' || TO_VARCHAR ( v_BUSINESS_DATE,
	 'YYYY-MM-DD' ) ) ELSE dsf_2.FX_RATE END ) ) as v_FXRATE,
	 '{{ var("ENTITY") }}' as o_ENTITY,
	 'LTD_STD' as o_LK_CALC_TYPE,
	 '{{ var("IRM_MARGINS_FILE_NAME") }}' as O_LK_FILE_NAME,
	 'RR_RATE_MARKET_MARGIN_FACT' as o_TARGET_TABLE,
	 '-2' as o_LK_EXCHANGE_MNEMONIC_CNTPRTY,
	 '-2' as o_LK_LCH_UNIQUE_ID,
	 UPPER ( LTRIM ( RTRIM ( MEMBER_MNEMONIC ) ) ) as o_LK_MEMBER_MNEMONIC,
	 '{{ var("BATCH_ID") }}' as o_BATCH_ID,
	 v_BUSINESS_DATE as o_BUSINESS_DATE,
	 LTRIM ( RTRIM ( UPPER ( DAY_PERIOD_TYPE_INDICATOR ) ) ) as o_DAY_PERIOD_TYPE_INDICATOR,
	 GRI_RUN_ID as o_GRI_RUN_ID,
	 LTRIM ( RTRIM ( UPPER ( MARGIN_GROUP ) ) ) as o_MARGIN_GROUP,
	 UPPER ( LTRIM ( RTRIM ( MARKET_ID ) ) ) as o_MARKET_ID,
	 LTRIM ( RTRIM ( TRADER_MNEMONIC ) ) as o_TRADER_MNEMONIC,
	 LTRIM ( RTRIM ( MARGIN_ACCOUNT_TYPE ) ) as o_ACCOUNT_TYPE,
	 ( CASE WHEN dsf_3.ID IS NULL THEN ABORT ( 'Error:ID Not found at CURRENCY_DIM for Currency:' || v_CURRENCY ) ELSE dsf_3.ID END ) as o_CURRENCY_ID,
	 ( CASE WHEN dsf_4.ID IS NULL THEN ABORT ( 'Error:ID Not found at CURRENCY_DIM for Base Currency:' || v_BASE_CURRENCY ) ELSE dsf_4.ID END ) as o_BASE_CURRENCY_ID,
	 v_FXRATE as o_FXRATE,
	 ( CASE WHEN TO_DECIMAL ( IM_TOTAL ) = 0 THEN 0 ELSE ( TO_DECIMAL ( IM_TOTAL ) * -1 ) END ) as o_IM,
	 ( CASE WHEN TO_DECIMAL ( IM_OPEN ) = 0 THEN 0 ELSE ( TO_DECIMAL ( IM_OPEN ) * -1 ) END ) as o_IM_OPEN,
	 ( CASE WHEN TO_DECIMAL ( IM_DELIVERY ) = 0 THEN 0 ELSE ( TO_DECIMAL ( IM_DELIVERY ) * -1 ) END ) as o_IM_DELIVERY,
	 VM as o_VM,
	 CVM as o_CVM,
	 NLV as o_NLV,
	 ESA as o_ESA,
	 CRIM as o_CRIM,
	 IMM as o_IMM,
	 DFAM as o_DFAM,
	 TO_DECIMAL ( IM_TOTAL,
	 10 ) * v_FXRATE * -1 as o_IM_FX,
	 TO_DECIMAL ( CRIM,
	 10 ) * v_FXRATE as o_CRIM_FX,
	 TO_DECIMAL ( IMM,
	 10 ) * v_FXRATE as o_IMM_FX,
	 LTRIM ( RTRIM ( PARTICIPANT_ROLE_TYPE ) ) as o_PARTICIPANT_ROLE_TYPE,
	 LTRIM ( RTRIM ( POSITION_ACCOUNT_TYPE ) ) as o_POSITION_ACCOUNT_TYPE,
	 LTRIM ( RTRIM ( CLIENT_IDENTIFIER ) ) as o_CLIENT_IDENTIFIER,
	 LTRIM ( RTRIM ( CLIENT_IDENTIFIER_TYPE ) ) as o_CLIENT_IDENTIFIER_TYPE,
	 IMM1 as o_IMM1,
	 OUTRIGHT_RATES_IMMFP as o_OUTRIGHT_RATES_IMMFP,
	 BASIS_IMMFP as o_BASIS_IMMFP,
	 OPTIONS_LIQUIDITY_MARGIN as o_OPTIONS_LIQUIDITY_MARGIN,
	 LCRM as o_LCRM,
	 OPTIONS_VOLATILITY_ADJUSTMENT as o_OPTIONS_VOLATILITY_ADJUSTMENT,
	 UNSCALED_VAR_ADDON as o_UNSCALED_VAR_ADDON,
	 NET_BH_TOTAL as o_NET_BH_TOTAL,
	 CCY_HOL_VM as o_CCY_HOL_VM,
	 TO_DECIMAL ( CCY_HOL_VM,
	 10 ) * v_FXRATE as o_CCY_HOL_VM_FX,
	 OPTION_PREMIUM as o_OPTION_PREMIUM,
	 FXAddOn as o_FXAddOn,
	 TO_DECIMAL ( FXAddOn,
	 10 ) * v_FXRATE as o_FXAddOn_FX,
	 1 as o_ACTIVE_FLAG,
	 v_TOT_REC_COUNT + 1 as v_TOT_REC_COUNT,
	 MER as MER,
	 TO_DECIMAL ( SPMAddon ) as o_SPMAddon 
From SQ_SC_IRM_MARGINS_YYYYMMDD_EODOut as SQ_SC_IRM_MARGINS_YYYYMMDD_EODOut 
LEFT JOIN (
SELECT STRING_VALUE, VARIABLE_NAME FROM (  SELECT STRING_VALUE, VARIABLE_NAME,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE, VARIABLE_NAME,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME ORDER BY VARIABLE_NAME NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.VARIABLE_NAME = 'RATE_MARKET_MARGIN_BASE_CURRENCY'
LEFT JOIN (
SELECT FX_RATE, TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME FROM (  SELECT FX_RATE, TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME,  ROW_NUMBER() OVER (PARTITION BY TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT FX_RATE, TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME,  ROW_NUMBER() OVER (PARTITION BY TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME ORDER BY TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    FX_RATE_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.TYPE = 'EOD' AND dsf_2.SOURCE_CURRENCY = v_CURRENCY AND dsf_2.TARGET_CURRENCY = v_BASE_CURRENCY AND dsf_2.BUSINESS_DATE_TIME = v_BUSINESS_DATE
LEFT JOIN (
SELECT ID, CURRENCY_MNEMONIC FROM (  SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY CURRENCY_MNEMONIC NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    CURRENCY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.CURRENCY_MNEMONIC = v_CURRENCY
LEFT JOIN (
SELECT ID, CURRENCY_MNEMONIC FROM (  SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY CURRENCY_MNEMONIC NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    CURRENCY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.CURRENCY_MNEMONIC = v_BASE_CURRENCY
Where MEMBER_MNEMONIC  !=  'XCH'),

exp_Populate_TargetOut2 as (
	/* transType: "Expression" */
Select 
	UPPER ( LTRIM ( RTRIM ( CURRENCY ) ) ) as v_CURRENCY,
	 UPPER ( LTRIM ( RTRIM ( dsf_1.STRING_VALUE ) ) ) as v_BASE_CURRENCY,
	 TO_DATE ( LTRIM ( RTRIM ( BUSINESS_DATE ) ),
	 'YYYYMMDD' ) as v_BUSINESS_DATE,
	 DECODE ( DAY_PERIOD_TYPE_INDICATOR,
	 'I',
	 0,
	 'E',
	 ( CASE WHEN dsf_2.FX_RATE IS NULL THEN ABORT ( 'Error:Fx-Rate returned null from FX_RATE_DIM for Type:EOD,Source Currency:' || v_CURRENCY || ' Target Currency:' || v_BASE_CURRENCY || ' and Business_Date:' || TO_VARCHAR ( v_BUSINESS_DATE,
	 'YYYY-MM-DD' ) ) ELSE dsf_2.FX_RATE END ) ) as v_FXRATE,
	 '{{ var("ENTITY") }}' as o_ENTITY,
	 'LTD_STD' as o_LK_CALC_TYPE,
	 '{{ var("IRM_MARGINS_FILE_NAME") }}' as O_LK_FILE_NAME,
	 'RR_RATE_MARKET_MARGIN_FACT' as o_TARGET_TABLE,
	 '-2' as o_LK_EXCHANGE_MNEMONIC_CNTPRTY,
	 '-2' as o_LK_LCH_UNIQUE_ID,
	 UPPER ( LTRIM ( RTRIM ( MEMBER_MNEMONIC ) ) ) as o_LK_MEMBER_MNEMONIC,
	 '{{ var("BATCH_ID") }}' as o_BATCH_ID,
	 v_BUSINESS_DATE as o_BUSINESS_DATE,
	 LTRIM ( RTRIM ( UPPER ( DAY_PERIOD_TYPE_INDICATOR ) ) ) as o_DAY_PERIOD_TYPE_INDICATOR,
	 GRI_RUN_ID as o_GRI_RUN_ID,
	 LTRIM ( RTRIM ( UPPER ( MARGIN_GROUP ) ) ) as o_MARGIN_GROUP,
	 UPPER ( LTRIM ( RTRIM ( MARKET_ID ) ) ) as o_MARKET_ID,
	 LTRIM ( RTRIM ( TRADER_MNEMONIC ) ) as o_TRADER_MNEMONIC,
	 LTRIM ( RTRIM ( MARGIN_ACCOUNT_TYPE ) ) as o_ACCOUNT_TYPE,
	 ( CASE WHEN dsf_3.ID IS NULL THEN ABORT ( 'Error:ID Not found at CURRENCY_DIM for Currency:' || v_CURRENCY ) ELSE dsf_3.ID END ) as o_CURRENCY_ID,
	 ( CASE WHEN dsf_4.ID IS NULL THEN ABORT ( 'Error:ID Not found at CURRENCY_DIM for Base Currency:' || v_BASE_CURRENCY ) ELSE dsf_4.ID END ) as o_BASE_CURRENCY_ID,
	 v_FXRATE as o_FXRATE,
	 ( CASE WHEN TO_DECIMAL ( IM_TOTAL ) = 0 THEN 0 ELSE ( TO_DECIMAL ( IM_TOTAL ) * -1 ) END ) as o_IM,
	 ( CASE WHEN TO_DECIMAL ( IM_OPEN ) = 0 THEN 0 ELSE ( TO_DECIMAL ( IM_OPEN ) * -1 ) END ) as o_IM_OPEN,
	 ( CASE WHEN TO_DECIMAL ( IM_DELIVERY ) = 0 THEN 0 ELSE ( TO_DECIMAL ( IM_DELIVERY ) * -1 ) END ) as o_IM_DELIVERY,
	 VM as o_VM,
	 CVM as o_CVM,
	 NLV as o_NLV,
	 ESA as o_ESA,
	 CRIM as o_CRIM,
	 IMM as o_IMM,
	 DFAM as o_DFAM,
	 TO_DECIMAL ( IM_TOTAL,
	 10 ) * v_FXRATE * -1 as o_IM_FX,
	 TO_DECIMAL ( CRIM,
	 10 ) * v_FXRATE as o_CRIM_FX,
	 TO_DECIMAL ( IMM,
	 10 ) * v_FXRATE as o_IMM_FX,
	 LTRIM ( RTRIM ( PARTICIPANT_ROLE_TYPE ) ) as o_PARTICIPANT_ROLE_TYPE,
	 LTRIM ( RTRIM ( POSITION_ACCOUNT_TYPE ) ) as o_POSITION_ACCOUNT_TYPE,
	 LTRIM ( RTRIM ( CLIENT_IDENTIFIER ) ) as o_CLIENT_IDENTIFIER,
	 LTRIM ( RTRIM ( CLIENT_IDENTIFIER_TYPE ) ) as o_CLIENT_IDENTIFIER_TYPE,
	 IMM1 as o_IMM1,
	 OUTRIGHT_RATES_IMMFP as o_OUTRIGHT_RATES_IMMFP,
	 BASIS_IMMFP as o_BASIS_IMMFP,
	 OPTIONS_LIQUIDITY_MARGIN as o_OPTIONS_LIQUIDITY_MARGIN,
	 LCRM as o_LCRM,
	 OPTIONS_VOLATILITY_ADJUSTMENT as o_OPTIONS_VOLATILITY_ADJUSTMENT,
	 UNSCALED_VAR_ADDON as o_UNSCALED_VAR_ADDON,
	 NET_BH_TOTAL as o_NET_BH_TOTAL,
	 CCY_HOL_VM as o_CCY_HOL_VM,
	 TO_DECIMAL ( CCY_HOL_VM,
	 10 ) * v_FXRATE as o_CCY_HOL_VM_FX,
	 OPTION_PREMIUM as o_OPTION_PREMIUM,
	 FXAddOn as o_FXAddOn,
	 TO_DECIMAL ( FXAddOn,
	 10 ) * v_FXRATE as o_FXAddOn_FX,
	 1 as o_ACTIVE_FLAG,
	 v_TOT_REC_COUNT + 1 as v_TOT_REC_COUNT,
	 MER as MER,
	 TO_DECIMAL ( SPMAddon ) as o_SPMAddon 
From SQ_SC_IRM_MARGINS_YYYYMMDD_EODOut as SQ_SC_IRM_MARGINS_YYYYMMDD_EODOut 
LEFT JOIN (
SELECT STRING_VALUE, VARIABLE_NAME FROM (  SELECT STRING_VALUE, VARIABLE_NAME,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE, VARIABLE_NAME,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME ORDER BY VARIABLE_NAME NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.VARIABLE_NAME = 'RATE_MARKET_MARGIN_BASE_CURRENCY'
LEFT JOIN (
SELECT FX_RATE, TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME FROM (  SELECT FX_RATE, TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME,  ROW_NUMBER() OVER (PARTITION BY TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT FX_RATE, TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME,  ROW_NUMBER() OVER (PARTITION BY TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME ORDER BY TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    FX_RATE_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.TYPE = 'EOD' AND dsf_2.SOURCE_CURRENCY = v_CURRENCY AND dsf_2.TARGET_CURRENCY = v_BASE_CURRENCY AND dsf_2.BUSINESS_DATE_TIME = v_BUSINESS_DATE
LEFT JOIN (
SELECT ID, CURRENCY_MNEMONIC FROM (  SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY CURRENCY_MNEMONIC NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    CURRENCY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.CURRENCY_MNEMONIC = v_CURRENCY
LEFT JOIN (
SELECT ID, CURRENCY_MNEMONIC FROM (  SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY CURRENCY_MNEMONIC NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    CURRENCY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.CURRENCY_MNEMONIC = v_BASE_CURRENCY
Where MEMBER_MNEMONIC  !=  'XCH'),

exp_Populate_TargetOut3 as (
	/* transType: "Expression" */
Select 
	UPPER ( LTRIM ( RTRIM ( CURRENCY ) ) ) as v_CURRENCY,
	 UPPER ( LTRIM ( RTRIM ( dsf_1.STRING_VALUE ) ) ) as v_BASE_CURRENCY,
	 TO_DATE ( LTRIM ( RTRIM ( BUSINESS_DATE ) ),
	 'YYYYMMDD' ) as v_BUSINESS_DATE,
	 DECODE ( DAY_PERIOD_TYPE_INDICATOR,
	 'I',
	 0,
	 'E',
	 ( CASE WHEN dsf_2.FX_RATE IS NULL THEN ABORT ( 'Error:Fx-Rate returned null from FX_RATE_DIM for Type:EOD,Source Currency:' || v_CURRENCY || ' Target Currency:' || v_BASE_CURRENCY || ' and Business_Date:' || TO_VARCHAR ( v_BUSINESS_DATE,
	 'YYYY-MM-DD' ) ) ELSE dsf_2.FX_RATE END ) ) as v_FXRATE,
	 '{{ var("ENTITY") }}' as o_ENTITY,
	 'LTD_STD' as o_LK_CALC_TYPE,
	 '{{ var("IRM_MARGINS_FILE_NAME") }}' as O_LK_FILE_NAME,
	 'RR_RATE_MARKET_MARGIN_FACT' as o_TARGET_TABLE,
	 '-2' as o_LK_EXCHANGE_MNEMONIC_CNTPRTY,
	 '-2' as o_LK_LCH_UNIQUE_ID,
	 UPPER ( LTRIM ( RTRIM ( MEMBER_MNEMONIC ) ) ) as o_LK_MEMBER_MNEMONIC,
	 '{{ var("BATCH_ID") }}' as o_BATCH_ID,
	 v_BUSINESS_DATE as o_BUSINESS_DATE,
	 LTRIM ( RTRIM ( UPPER ( DAY_PERIOD_TYPE_INDICATOR ) ) ) as o_DAY_PERIOD_TYPE_INDICATOR,
	 GRI_RUN_ID as o_GRI_RUN_ID,
	 LTRIM ( RTRIM ( UPPER ( MARGIN_GROUP ) ) ) as o_MARGIN_GROUP,
	 UPPER ( LTRIM ( RTRIM ( MARKET_ID ) ) ) as o_MARKET_ID,
	 LTRIM ( RTRIM ( TRADER_MNEMONIC ) ) as o_TRADER_MNEMONIC,
	 LTRIM ( RTRIM ( MARGIN_ACCOUNT_TYPE ) ) as o_ACCOUNT_TYPE,
	 ( CASE WHEN dsf_3.ID IS NULL THEN ABORT ( 'Error:ID Not found at CURRENCY_DIM for Currency:' || v_CURRENCY ) ELSE dsf_3.ID END ) as o_CURRENCY_ID,
	 ( CASE WHEN dsf_4.ID IS NULL THEN ABORT ( 'Error:ID Not found at CURRENCY_DIM for Base Currency:' || v_BASE_CURRENCY ) ELSE dsf_4.ID END ) as o_BASE_CURRENCY_ID,
	 v_FXRATE as o_FXRATE,
	 ( CASE WHEN TO_DECIMAL ( IM_TOTAL ) = 0 THEN 0 ELSE ( TO_DECIMAL ( IM_TOTAL ) * -1 ) END ) as o_IM,
	 ( CASE WHEN TO_DECIMAL ( IM_OPEN ) = 0 THEN 0 ELSE ( TO_DECIMAL ( IM_OPEN ) * -1 ) END ) as o_IM_OPEN,
	 ( CASE WHEN TO_DECIMAL ( IM_DELIVERY ) = 0 THEN 0 ELSE ( TO_DECIMAL ( IM_DELIVERY ) * -1 ) END ) as o_IM_DELIVERY,
	 VM as o_VM,
	 CVM as o_CVM,
	 NLV as o_NLV,
	 ESA as o_ESA,
	 CRIM as o_CRIM,
	 IMM as o_IMM,
	 DFAM as o_DFAM,
	 TO_DECIMAL ( IM_TOTAL,
	 10 ) * v_FXRATE * -1 as o_IM_FX,
	 TO_DECIMAL ( CRIM,
	 10 ) * v_FXRATE as o_CRIM_FX,
	 TO_DECIMAL ( IMM,
	 10 ) * v_FXRATE as o_IMM_FX,
	 LTRIM ( RTRIM ( PARTICIPANT_ROLE_TYPE ) ) as o_PARTICIPANT_ROLE_TYPE,
	 LTRIM ( RTRIM ( POSITION_ACCOUNT_TYPE ) ) as o_POSITION_ACCOUNT_TYPE,
	 LTRIM ( RTRIM ( CLIENT_IDENTIFIER ) ) as o_CLIENT_IDENTIFIER,
	 LTRIM ( RTRIM ( CLIENT_IDENTIFIER_TYPE ) ) as o_CLIENT_IDENTIFIER_TYPE,
	 IMM1 as o_IMM1,
	 OUTRIGHT_RATES_IMMFP as o_OUTRIGHT_RATES_IMMFP,
	 BASIS_IMMFP as o_BASIS_IMMFP,
	 OPTIONS_LIQUIDITY_MARGIN as o_OPTIONS_LIQUIDITY_MARGIN,
	 LCRM as o_LCRM,
	 OPTIONS_VOLATILITY_ADJUSTMENT as o_OPTIONS_VOLATILITY_ADJUSTMENT,
	 UNSCALED_VAR_ADDON as o_UNSCALED_VAR_ADDON,
	 NET_BH_TOTAL as o_NET_BH_TOTAL,
	 CCY_HOL_VM as o_CCY_HOL_VM,
	 TO_DECIMAL ( CCY_HOL_VM,
	 10 ) * v_FXRATE as o_CCY_HOL_VM_FX,
	 OPTION_PREMIUM as o_OPTION_PREMIUM,
	 FXAddOn as o_FXAddOn,
	 TO_DECIMAL ( FXAddOn,
	 10 ) * v_FXRATE as o_FXAddOn_FX,
	 1 as o_ACTIVE_FLAG,
	 v_TOT_REC_COUNT + 1 as v_TOT_REC_COUNT,
	 MER as MER,
	 TO_DECIMAL ( SPMAddon ) as o_SPMAddon 
From SQ_SC_IRM_MARGINS_YYYYMMDD_EODOut as SQ_SC_IRM_MARGINS_YYYYMMDD_EODOut 
LEFT JOIN (
SELECT STRING_VALUE, VARIABLE_NAME FROM (  SELECT STRING_VALUE, VARIABLE_NAME,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE, VARIABLE_NAME,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME ORDER BY VARIABLE_NAME NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.VARIABLE_NAME = 'RATE_MARKET_MARGIN_BASE_CURRENCY'
LEFT JOIN (
SELECT FX_RATE, TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME FROM (  SELECT FX_RATE, TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME,  ROW_NUMBER() OVER (PARTITION BY TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT FX_RATE, TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME,  ROW_NUMBER() OVER (PARTITION BY TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME ORDER BY TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    FX_RATE_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.TYPE = 'EOD' AND dsf_2.SOURCE_CURRENCY = v_CURRENCY AND dsf_2.TARGET_CURRENCY = v_BASE_CURRENCY AND dsf_2.BUSINESS_DATE_TIME = v_BUSINESS_DATE
LEFT JOIN (
SELECT ID, CURRENCY_MNEMONIC FROM (  SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY CURRENCY_MNEMONIC NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    CURRENCY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.CURRENCY_MNEMONIC = v_CURRENCY
LEFT JOIN (
SELECT ID, CURRENCY_MNEMONIC FROM (  SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY CURRENCY_MNEMONIC NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    CURRENCY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.CURRENCY_MNEMONIC = v_BASE_CURRENCY
Where MEMBER_MNEMONIC  !=  'XCH'),

exp_Populate_TargetOut4 as (
	/* transType: "Expression" */
Select 
	UPPER ( LTRIM ( RTRIM ( CURRENCY ) ) ) as v_CURRENCY,
	 UPPER ( LTRIM ( RTRIM ( dsf_1.STRING_VALUE ) ) ) as v_BASE_CURRENCY,
	 TO_DATE ( LTRIM ( RTRIM ( BUSINESS_DATE ) ),
	 'YYYYMMDD' ) as v_BUSINESS_DATE,
	 DECODE ( DAY_PERIOD_TYPE_INDICATOR,
	 'I',
	 0,
	 'E',
	 ( CASE WHEN dsf_2.FX_RATE IS NULL THEN ABORT ( 'Error:Fx-Rate returned null from FX_RATE_DIM for Type:EOD,Source Currency:' || v_CURRENCY || ' Target Currency:' || v_BASE_CURRENCY || ' and Business_Date:' || TO_VARCHAR ( v_BUSINESS_DATE,
	 'YYYY-MM-DD' ) ) ELSE dsf_2.FX_RATE END ) ) as v_FXRATE,
	 '{{ var("ENTITY") }}' as o_ENTITY,
	 'LTD_STD' as o_LK_CALC_TYPE,
	 '{{ var("IRM_MARGINS_FILE_NAME") }}' as O_LK_FILE_NAME,
	 'RR_RATE_MARKET_MARGIN_FACT' as o_TARGET_TABLE,
	 '-2' as o_LK_EXCHANGE_MNEMONIC_CNTPRTY,
	 '-2' as o_LK_LCH_UNIQUE_ID,
	 UPPER ( LTRIM ( RTRIM ( MEMBER_MNEMONIC ) ) ) as o_LK_MEMBER_MNEMONIC,
	 '{{ var("BATCH_ID") }}' as o_BATCH_ID,
	 v_BUSINESS_DATE as o_BUSINESS_DATE,
	 LTRIM ( RTRIM ( UPPER ( DAY_PERIOD_TYPE_INDICATOR ) ) ) as o_DAY_PERIOD_TYPE_INDICATOR,
	 GRI_RUN_ID as o_GRI_RUN_ID,
	 LTRIM ( RTRIM ( UPPER ( MARGIN_GROUP ) ) ) as o_MARGIN_GROUP,
	 UPPER ( LTRIM ( RTRIM ( MARKET_ID ) ) ) as o_MARKET_ID,
	 LTRIM ( RTRIM ( TRADER_MNEMONIC ) ) as o_TRADER_MNEMONIC,
	 LTRIM ( RTRIM ( MARGIN_ACCOUNT_TYPE ) ) as o_ACCOUNT_TYPE,
	 ( CASE WHEN dsf_3.ID IS NULL THEN ABORT ( 'Error:ID Not found at CURRENCY_DIM for Currency:' || v_CURRENCY ) ELSE dsf_3.ID END ) as o_CURRENCY_ID,
	 ( CASE WHEN dsf_4.ID IS NULL THEN ABORT ( 'Error:ID Not found at CURRENCY_DIM for Base Currency:' || v_BASE_CURRENCY ) ELSE dsf_4.ID END ) as o_BASE_CURRENCY_ID,
	 v_FXRATE as o_FXRATE,
	 ( CASE WHEN TO_DECIMAL ( IM_TOTAL ) = 0 THEN 0 ELSE ( TO_DECIMAL ( IM_TOTAL ) * -1 ) END ) as o_IM,
	 ( CASE WHEN TO_DECIMAL ( IM_OPEN ) = 0 THEN 0 ELSE ( TO_DECIMAL ( IM_OPEN ) * -1 ) END ) as o_IM_OPEN,
	 ( CASE WHEN TO_DECIMAL ( IM_DELIVERY ) = 0 THEN 0 ELSE ( TO_DECIMAL ( IM_DELIVERY ) * -1 ) END ) as o_IM_DELIVERY,
	 VM as o_VM,
	 CVM as o_CVM,
	 NLV as o_NLV,
	 ESA as o_ESA,
	 CRIM as o_CRIM,
	 IMM as o_IMM,
	 DFAM as o_DFAM,
	 TO_DECIMAL ( IM_TOTAL,
	 10 ) * v_FXRATE * -1 as o_IM_FX,
	 TO_DECIMAL ( CRIM,
	 10 ) * v_FXRATE as o_CRIM_FX,
	 TO_DECIMAL ( IMM,
	 10 ) * v_FXRATE as o_IMM_FX,
	 LTRIM ( RTRIM ( PARTICIPANT_ROLE_TYPE ) ) as o_PARTICIPANT_ROLE_TYPE,
	 LTRIM ( RTRIM ( POSITION_ACCOUNT_TYPE ) ) as o_POSITION_ACCOUNT_TYPE,
	 LTRIM ( RTRIM ( CLIENT_IDENTIFIER ) ) as o_CLIENT_IDENTIFIER,
	 LTRIM ( RTRIM ( CLIENT_IDENTIFIER_TYPE ) ) as o_CLIENT_IDENTIFIER_TYPE,
	 IMM1 as o_IMM1,
	 OUTRIGHT_RATES_IMMFP as o_OUTRIGHT_RATES_IMMFP,
	 BASIS_IMMFP as o_BASIS_IMMFP,
	 OPTIONS_LIQUIDITY_MARGIN as o_OPTIONS_LIQUIDITY_MARGIN,
	 LCRM as o_LCRM,
	 OPTIONS_VOLATILITY_ADJUSTMENT as o_OPTIONS_VOLATILITY_ADJUSTMENT,
	 UNSCALED_VAR_ADDON as o_UNSCALED_VAR_ADDON,
	 NET_BH_TOTAL as o_NET_BH_TOTAL,
	 CCY_HOL_VM as o_CCY_HOL_VM,
	 TO_DECIMAL ( CCY_HOL_VM,
	 10 ) * v_FXRATE as o_CCY_HOL_VM_FX,
	 OPTION_PREMIUM as o_OPTION_PREMIUM,
	 FXAddOn as o_FXAddOn,
	 TO_DECIMAL ( FXAddOn,
	 10 ) * v_FXRATE as o_FXAddOn_FX,
	 1 as o_ACTIVE_FLAG,
	 v_TOT_REC_COUNT + 1 as v_TOT_REC_COUNT,
	 MER as MER,
	 TO_DECIMAL ( SPMAddon ) as o_SPMAddon 
From SQ_SC_IRM_MARGINS_YYYYMMDD_EODOut as SQ_SC_IRM_MARGINS_YYYYMMDD_EODOut 
LEFT JOIN (
SELECT STRING_VALUE, VARIABLE_NAME FROM (  SELECT STRING_VALUE, VARIABLE_NAME,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE, VARIABLE_NAME,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME ORDER BY VARIABLE_NAME NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.VARIABLE_NAME = 'RATE_MARKET_MARGIN_BASE_CURRENCY'
LEFT JOIN (
SELECT FX_RATE, TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME FROM (  SELECT FX_RATE, TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME,  ROW_NUMBER() OVER (PARTITION BY TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT FX_RATE, TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME,  ROW_NUMBER() OVER (PARTITION BY TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME ORDER BY TYPE, SOURCE_CURRENCY, TARGET_CURRENCY, BUSINESS_DATE_TIME NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    FX_RATE_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.TYPE = 'EOD' AND dsf_2.SOURCE_CURRENCY = v_CURRENCY AND dsf_2.TARGET_CURRENCY = v_BASE_CURRENCY AND dsf_2.BUSINESS_DATE_TIME = v_BUSINESS_DATE
LEFT JOIN (
SELECT ID, CURRENCY_MNEMONIC FROM (  SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY CURRENCY_MNEMONIC NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    CURRENCY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.CURRENCY_MNEMONIC = v_CURRENCY
LEFT JOIN (
SELECT ID, CURRENCY_MNEMONIC FROM (  SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY CURRENCY_MNEMONIC NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    CURRENCY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.CURRENCY_MNEMONIC = v_BASE_CURRENCY
Where MEMBER_MNEMONIC  !=  'XCH'),

SC_LKP_ENTITY_DIMOut as (
	/* transType: "Lookup Procedure" */
Select 
	DIMENSION_KEY as DIMENSION_KEY,
	 exp_Populate_Target.o_ENTITY AS i_NAME,
	 exp_Populate_Target.o_BUSINESS_DATE AS i_DATE 
FROM
	exp_Populate_TargetOut1 as exp_Populate_TargetOut1 
 LEFT JOIN ( select * from (
select 
*,NAME,EFFECTIVE_DATE,EXPIRATION_DATE,row_number() over(partition by NAME,EFFECTIVE_DATE,EXPIRATION_DATE order by rnk_fst desc nulls last) as rnk_lst
from
(
select *,NAME,EFFECTIVE_DATE,EXPIRATION_DATE,row_number() over(partition by NAME,EFFECTIVE_DATE,EXPIRATION_DATE order by NAME,EFFECTIVE_DATE,EXPIRATION_DATE nulls last) as rnk_fst
from ( SELECT
    ENTITY_DIM.DIMENSION_KEY as DIMENSION_KEY,
    ENTITY_DIM.NAME as NAME,
    ENTITY_DIM.EFFECTIVE_DATE as EFFECTIVE_DATE,
    NVL(ENTITY_DIM.EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) as EXPIRATION_DATE
 FROM
    ENTITY_DIM )
) lkp_inner
) lkp_outer
where rnk_lst=1 ) 
ON
	NAME = i_NAME
	AND EFFECTIVE_DATE <= i_DATE
	AND EXPIRATION_DATE >= i_DATE
 
),

EXP_EPOC_FORMATOut as (
	/* transType: "Expression" */
Select 
	LPAD ( GENERATED_SEQ,
	 9,
	 '0' ) as v_SEQ_LPAD_TO_9,
	 DATEDIFF ( SECOND,
	 TO_TIMESTAMP ( '01/01/1970 00:00:00',
	 'DD-MM-YYYY HH24:MI:SS' ),
	 dsCurrentTimestamp ( ) ) as v_EPOC_TIME,
	 v_EPOC_TIME || v_SEQ_LPAD_TO_9 as v_CONCATE_ID,
	 v_CONCATE_ID as ID
From DSR_EXP_EPOC_FORMATOut as DSR_EXP_EPOC_FORMATOut),

SC_LKP_CALENDAR_DIM_IRMOut as (
	/* transType: "Lookup Procedure" */
Select 
	ID as ID,
	 NAME as NAME,
	 DESCRIPTION as DESCRIPTION,
	 TYPE as TYPE,
	 CAL_DATE as CAL_DATE,
	 DAY_NAME as DAY_NAME,
	 WEEK_NUMBER as WEEK_NUMBER,
	 MONTH_NUMBER as MONTH_NUMBER,
	 MONTH_NAME as MONTH_NAME,
	 QUARTER as QUARTER,
	 YEAR as YEAR,
	 YEAR_MONTH as YEAR_MONTH,
	 YEAR_QUARTER as YEAR_QUARTER,
	 WEEKEND_IND as WEEKEND_IND,
	 LCH_WORKING_DAY_IND as LCH_WORKING_DAY_IND,
	 LCH_HOLIDAY_IND as LCH_HOLIDAY_IND,
	 EXTERNAL_WORKING_DAY_IND as EXTERNAL_WORKING_DAY_IND,
	 EXTERNAL_HOLIDAY_IND as EXTERNAL_HOLIDAY_IND,
	 exp_Populate_TargetOut.i_CAL_TYPE as i_CAL_TYPE_1,
	 exp_Populate_TargetOut.i_DATE as i_DATE_1,
	 exp_Populate_Target.o_LK_CALC_TYPE AS i_CAL_TYPE_2,
	 exp_Populate_Target.o_BUSINESS_DATE AS i_DATE_2 
FROM
	exp_Populate_TargetOut2 as exp_Populate_TargetOut2 
 LEFT JOIN CALENDAR_DIMOut
ON
	CAL_DATE = i_DATE
	AND TYPE = i_CAL_TYPE
 
),

SC_LKP_COUNTERPARTIES_DIM_MBR_CPTY_IDOut as (
	/* transType: "Lookup Procedure" */
Select 
	ID as ID,
	 exp_Populate_Target.o_LK_EXCHANGE_MNEMONIC_CNTPRTY AS i_EXCHANGE_MNEMONIC,
	 exp_Populate_Target.o_LK_LCH_UNIQUE_ID AS i_LCH_UNIQUE_ID,
	 exp_Populate_Target.o_LK_MEMBER_MNEMONIC AS i_CLEARING_MEMBER_MNEMONIC,
	 exp_Populate_Target.o_BUSINESS_DATE AS i_DATE 
FROM
	exp_Populate_TargetOut4 as exp_Populate_TargetOut4 
 LEFT JOIN ( select * from (
select 
*,EXCHANGE_MNEMONIC,LCH_UNIQUE_ID,CLEARING_MEMBER_MNEMONIC,EFFECTIVE_FROM_DATE,EFFECTIVE_TO_DATE,row_number() over(partition by EXCHANGE_MNEMONIC,LCH_UNIQUE_ID,CLEARING_MEMBER_MNEMONIC,EFFECTIVE_FROM_DATE,EFFECTIVE_TO_DATE order by rnk_fst desc nulls last) as rnk_lst
from
(
select *,EXCHANGE_MNEMONIC,LCH_UNIQUE_ID,CLEARING_MEMBER_MNEMONIC,EFFECTIVE_FROM_DATE,EFFECTIVE_TO_DATE,row_number() over(partition by EXCHANGE_MNEMONIC,LCH_UNIQUE_ID,CLEARING_MEMBER_MNEMONIC,EFFECTIVE_FROM_DATE,EFFECTIVE_TO_DATE order by EXCHANGE_MNEMONIC,LCH_UNIQUE_ID,CLEARING_MEMBER_MNEMONIC,EFFECTIVE_FROM_DATE,EFFECTIVE_TO_DATE nulls last) as rnk_fst
from ( SELECT
    COUNTERPARTIES_DIM.ID as ID,
    COUNTERPARTIES_DIM.EXCHANGE_MNEMONIC as EXCHANGE_MNEMONIC,
    COUNTERPARTIES_DIM.LCH_UNIQUE_ID as LCH_UNIQUE_ID,
    COUNTERPARTIES_DIM.CLEARING_MEMBER_MNEMONIC as CLEARING_MEMBER_MNEMONIC,
    COUNTERPARTIES_DIM.EFFECTIVE_FROM_DATE as EFFECTIVE_FROM_DATE,
    NVL(COUNTERPARTIES_DIM.EFFECTIVE_TO_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) as EFFECTIVE_TO_DATE
 FROM
    COUNTERPARTIES_DIM )
) lkp_inner
) lkp_outer
where rnk_lst=1 ) 
ON
	EXCHANGE_MNEMONIC = i_EXCHANGE_MNEMONIC
	AND LCH_UNIQUE_ID = i_LCH_UNIQUE_ID
	AND CLEARING_MEMBER_MNEMONIC = i_CLEARING_MEMBER_MNEMONIC
	AND EFFECTIVE_FROM_DATE <= i_DATE
	AND EFFECTIVE_TO_DATE >= i_DATE
 
),

SC_LKP_BATCH_DETAILS_IDOut as (
	/* transType: "Lookup Procedure" */
Select 
	ID as ID,
	 BATCH_ID as BATCH_ID,
	 TARGET_TABLE_NAME as TARGET_TABLE_NAME,
	 FILE_NAME as FILE_NAME,
	 STATUS as STATUS,
	 exp_Populate_Target.o_BATCH_ID AS in_BATCH_ID,
	 exp_Populate_Target.o_TARGET_TABLE AS in_TARGET_TABLE_NAME,
	 exp_Populate_Target.O_LK_FILE_NAME AS in_SOURCE_NAME 
FROM
	exp_Populate_TargetOut as exp_Populate_TargetOut 
 LEFT JOIN ( select * from (
select 
*,BATCH_ID,TARGET_TABLE_NAME,FILE_NAME,row_number() over(partition by BATCH_ID,TARGET_TABLE_NAME,FILE_NAME order by rnk_fst desc nulls last) as rnk_lst
from
(
select *,BATCH_ID,TARGET_TABLE_NAME,FILE_NAME,row_number() over(partition by BATCH_ID,TARGET_TABLE_NAME,FILE_NAME order by BATCH_ID,TARGET_TABLE_NAME,FILE_NAME nulls last) as rnk_fst
from ( SELECT
    BATCH_DETAILS.ID as ID,
    BATCH_DETAILS.BATCH_ID as BATCH_ID,
    BATCH_DETAILS.TARGET_TABLE_NAME as TARGET_TABLE_NAME,
    BATCH_DETAILS.FILE_NAME as FILE_NAME,
    BATCH_DETAILS.STATUS as STATUS
 FROM
 (SELECT
    id,
    TARGET_TABLE_NAME,
    BATCH_ID,
    STATUS,
    ACTIVE_FLAG,
    BATCH_DETAILS_START_TIME,
    FILE_NAME,
    RANK() OVER(partition by batch_id,TARGET_TABLE_NAME,FILE_NAME order by BATCH_DETAILS_START_TIME DESC) as RANK
 FROM
    BATCH_DETAILS) BATCH_DETAILS
 WHERE  
  RANK= 1 AND 
  STATUS= 'I' AND 
  ACTIVE_FLAG= 1 )
) lkp_inner
) lkp_outer
where rnk_lst=1 ) 
ON
	BATCH_ID = in_BATCH_ID
	AND TARGET_TABLE_NAME = in_TARGET_TABLE_NAME
	AND FILE_NAME = in_SOURCE_NAME
 
),

SC_LKP_BATCH_DETAILS_ID_details as (
  Select
  	SC_LKP_BATCH_DETAILS_IDOut.ID as BATCH_DETAILS_ID
  From SC_LKP_BATCH_DETAILS_IDOut as SC_LKP_BATCH_DETAILS_IDOut
),

exp_Populate_Target_master as (
  Select
  	exp_Populate_TargetOut.o_BATCH_ID as BATCH_ID,
	 exp_Populate_TargetOut.o_BUSINESS_DATE as BUSINESS_DATE_TIME,
	 exp_Populate_TargetOut.o_DAY_PERIOD_TYPE_INDICATOR as DAY_PERIOD_TYPE_INDICATOR,
	 exp_Populate_TargetOut.o_GRI_RUN_ID as GRI_RUN_ID,
	 exp_Populate_TargetOut.o_MARGIN_GROUP as MARGIN_GROUP,
	 exp_Populate_TargetOut.o_MARKET_ID as MARKET_ID,
	 exp_Populate_TargetOut.o_TRADER_MNEMONIC as TRADER_MNEMONIC,
	 exp_Populate_TargetOut.o_ACCOUNT_TYPE as ACCOUNT_TYPE,
	 exp_Populate_TargetOut.o_CURRENCY_ID as CURRENCY_ID,
	 exp_Populate_TargetOut.o_BASE_CURRENCY_ID as BASE_CURRENCY_ID,
	 exp_Populate_TargetOut.o_FXRATE as FXRATE,
	 exp_Populate_TargetOut.o_IM as IM,
	 exp_Populate_TargetOut.o_IM_OPEN as IM_OPEN,
	 exp_Populate_TargetOut.o_IM_DELIVERY as IM_DELIVERY,
	 exp_Populate_TargetOut.o_VM as VM,
	 exp_Populate_TargetOut.o_CVM as CVM,
	 exp_Populate_TargetOut.o_NLV as NLV,
	 exp_Populate_TargetOut.o_ESA as ESA,
	 exp_Populate_TargetOut.o_CRIM as CRIM,
	 exp_Populate_TargetOut.o_IMM as IMM,
	 exp_Populate_TargetOut.o_DFAM as DFAM,
	 exp_Populate_TargetOut.o_IM_FX as IM_FX,
	 exp_Populate_TargetOut.o_CRIM_FX as CRIM_FX,
	 exp_Populate_TargetOut.o_IMM_FX as IMM_FX,
	 exp_Populate_TargetOut.o_PARTICIPANT_ROLE_TYPE as PARTICIPANT_ROLE_TYPE,
	 exp_Populate_TargetOut.o_POSITION_ACCOUNT_TYPE as POSITION_ACCOUNT_TYPE,
	 exp_Populate_TargetOut.o_CLIENT_IDENTIFIER as CLIENT_IDENTIFIER,
	 exp_Populate_TargetOut.o_CLIENT_IDENTIFIER_TYPE as CLIENT_IDENTIFIER_TYPE,
	 exp_Populate_TargetOut.o_IMM1 as IMM1,
	 exp_Populate_TargetOut.o_OUTRIGHT_RATES_IMMFP as OUTRIGHT_RATES_IMMFP,
	 exp_Populate_TargetOut.o_BASIS_IMMFP as BASIS_IMMFP,
	 exp_Populate_TargetOut.o_OPTIONS_LIQUIDITY_MARGIN as OPTIONS_LIQUIDITY_MARGIN,
	 exp_Populate_TargetOut.o_LCRM as LCRM,
	 exp_Populate_TargetOut.o_OPTIONS_VOLATILITY_ADJUSTMENT as OPTIONS_VOLATILITY_ADJ,
	 exp_Populate_TargetOut.o_UNSCALED_VAR_ADDON as UNSCALED_VAR_ADDON,
	 exp_Populate_TargetOut.o_NET_BH_TOTAL as NET_BH_TOTAL,
	 exp_Populate_TargetOut.o_CCY_HOL_VM as CCY_HOL_VM,
	 exp_Populate_TargetOut.o_CCY_HOL_VM_FX as CCY_HOL_VM_FX,
	 exp_Populate_TargetOut.o_OPTION_PREMIUM as OPTIONS_PREMIUM,
	 exp_Populate_TargetOut.o_ACTIVE_FLAG as ACTIVE_FLAG,
	 exp_Populate_TargetOut.o_FXAddOn as FX_ADDON,
	 exp_Populate_TargetOut.o_FXAddOn_FX as FX_ADDON_FX,
	 exp_Populate_TargetOut.MER as MER,
	 exp_Populate_TargetOut.o_SPMAddon as SPMAddon
  From exp_Populate_TargetOut as exp_Populate_TargetOut
),

SC_LKP_CALENDAR_DIM_IRM_details as (
  Select
  	SC_LKP_CALENDAR_DIM_IRMOut.ID as BUSINESS_DATE_ID
  From SC_LKP_CALENDAR_DIM_IRMOut as SC_LKP_CALENDAR_DIM_IRMOut
),

SC_LKP_ENTITY_DIM_details as (
  Select
  	SC_LKP_ENTITY_DIMOut.DIMENSION_KEY as ENTITY_ID
  From SC_LKP_ENTITY_DIMOut as SC_LKP_ENTITY_DIMOut
),

SC_LKP_COUNTERPARTIES_DIM_MBR_CPTY_ID_details as (
  Select
  	SC_LKP_COUNTERPARTIES_DIM_MBR_CPTY_IDOut.ID as MEMBER_COUNTERPARTY_ID
  From SC_LKP_COUNTERPARTIES_DIM_MBR_CPTY_IDOut as SC_LKP_COUNTERPARTIES_DIM_MBR_CPTY_IDOut
),
dsJoiner_SC_RR_RATE_MARKET_MARGIN_FACT0Out as (
	/* transType: "Joiner" */
Select 
	EXP_EPOC_FORMATOut.ID as ID,
	 exp_Populate_TargetOut3.o_BATCH_ID as BATCH_ID,
	 exp_Populate_TargetOut3.o_BUSINESS_DATE as BUSINESS_DATE_TIME,
	 SC_LKP_CALENDAR_DIM_IRM_details.BUSINESS_DATE_ID as BUSINESS_DATE_ID,
	 exp_Populate_TargetOut3.o_DAY_PERIOD_TYPE_INDICATOR as DAY_PERIOD_TYPE_INDICATOR,
	 exp_Populate_TargetOut3.o_GRI_RUN_ID as GRI_RUN_ID,
	 exp_Populate_TargetOut3.o_MARGIN_GROUP as MARGIN_GROUP,
	 exp_Populate_TargetOut3.o_MARKET_ID as MARKET_ID,
	 SC_LKP_COUNTERPARTIES_DIM_MBR_CPTY_ID_details.MEMBER_COUNTERPARTY_ID as MEMBER_COUNTERPARTY_ID,
	 exp_Populate_TargetOut3.o_TRADER_MNEMONIC as TRADER_MNEMONIC,
	 exp_Populate_TargetOut3.o_ACCOUNT_TYPE as ACCOUNT_TYPE,
	 exp_Populate_TargetOut3.o_CURRENCY_ID as CURRENCY_ID,
	 exp_Populate_TargetOut3.o_BASE_CURRENCY_ID as BASE_CURRENCY_ID,
	 exp_Populate_TargetOut3.o_FXRATE as FXRATE,
	 exp_Populate_TargetOut3.o_IM as IM,
	 exp_Populate_TargetOut3.o_IM_OPEN as IM_OPEN,
	 exp_Populate_TargetOut3.o_IM_DELIVERY as IM_DELIVERY,
	 exp_Populate_TargetOut3.o_VM as VM,
	 exp_Populate_TargetOut3.o_CVM as CVM,
	 exp_Populate_TargetOut3.o_NLV as NLV,
	 exp_Populate_TargetOut3.o_ESA as ESA,
	 exp_Populate_TargetOut3.o_CRIM as CRIM,
	 exp_Populate_TargetOut3.o_IMM as IMM,
	 exp_Populate_TargetOut3.o_DFAM as DFAM,
	 exp_Populate_TargetOut3.o_IM_FX as IM_FX,
	 exp_Populate_TargetOut3.o_CRIM_FX as CRIM_FX,
	 exp_Populate_TargetOut3.o_IMM_FX as IMM_FX,
	 exp_Populate_TargetOut3.o_PARTICIPANT_ROLE_TYPE as PARTICIPANT_ROLE_TYPE,
	 exp_Populate_TargetOut3.o_POSITION_ACCOUNT_TYPE as POSITION_ACCOUNT_TYPE,
	 exp_Populate_TargetOut3.o_CLIENT_IDENTIFIER as CLIENT_IDENTIFIER,
	 exp_Populate_TargetOut3.o_CLIENT_IDENTIFIER_TYPE as CLIENT_IDENTIFIER_TYPE,
	 exp_Populate_TargetOut3.o_IMM1 as IMM1,
	 exp_Populate_TargetOut3.o_OUTRIGHT_RATES_IMMFP as OUTRIGHT_RATES_IMMFP,
	 exp_Populate_TargetOut3.o_BASIS_IMMFP as BASIS_IMMFP,
	 exp_Populate_TargetOut3.o_OPTIONS_LIQUIDITY_MARGIN as OPTIONS_LIQUIDITY_MARGIN,
	 exp_Populate_TargetOut3.o_LCRM as LCRM,
	 exp_Populate_TargetOut3.o_OPTIONS_VOLATILITY_ADJUSTMENT as OPTIONS_VOLATILITY_ADJ,
	 exp_Populate_TargetOut3.o_UNSCALED_VAR_ADDON as UNSCALED_VAR_ADDON,
	 SC_LKP_BATCH_DETAILS_ID_details.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 SC_LKP_ENTITY_DIM_details.ENTITY_ID as ENTITY_ID,
	 exp_Populate_TargetOut3.o_NET_BH_TOTAL as NET_BH_TOTAL,
	 exp_Populate_TargetOut3.o_CCY_HOL_VM as CCY_HOL_VM,
	 exp_Populate_TargetOut3.o_CCY_HOL_VM_FX as CCY_HOL_VM_FX,
	 exp_Populate_TargetOut3.o_OPTION_PREMIUM as OPTIONS_PREMIUM,
	 exp_Populate_TargetOut3.o_ACTIVE_FLAG as ACTIVE_FLAG,
	 exp_Populate_TargetOut3.o_FXAddOn as FX_ADDON,
	 exp_Populate_TargetOut3.o_FXAddOn_FX as FX_ADDON_FX,
	 exp_Populate_TargetOut3.MER as MER,
	 exp_Populate_TargetOut3.o_SPMAddon as SPMAddon,
	 ROW_NUMBER ( ) OVER ( ORDER BY 1 ) as jkey 
From
exp_Populate_TargetOut3 as exp_Populate_TargetOut3 INNER JOIN SC_LKP_COUNTERPARTIES_DIM_MBR_CPTY_ID_details as SC_LKP_COUNTERPARTIES_DIM_MBR_CPTY_ID_details 
ON
exp_Populate_TargetOut3.jkey = SC_LKP_COUNTERPARTIES_DIM_MBR_CPTY_ID_details.jkey
 INNER JOIN SC_LKP_BATCH_DETAILS_ID_details as SC_LKP_BATCH_DETAILS_ID_details 
ON
exp_Populate_TargetOut3.jkey = SC_LKP_BATCH_DETAILS_ID_details.jkey
 INNER JOIN EXP_EPOC_FORMATOut as EXP_EPOC_FORMATOut 
ON
exp_Populate_TargetOut3.jkey = EXP_EPOC_FORMATOut.jkey
 INNER JOIN SC_LKP_ENTITY_DIM_details as SC_LKP_ENTITY_DIM_details 
ON
exp_Populate_TargetOut3.jkey = SC_LKP_ENTITY_DIM_details.jkey
 INNER JOIN SC_LKP_CALENDAR_DIM_IRM_details as SC_LKP_CALENDAR_DIM_IRM_details 
ON
exp_Populate_TargetOut3.jkey = SC_LKP_CALENDAR_DIM_IRM_details.jkey
 
)

Select 
	ID as ID,
	BATCH_ID as BATCH_ID,
	BUSINESS_DATE_TIME as BUSINESS_DATE_TIME,
	BUSINESS_DATE_ID as BUSINESS_DATE_ID,
	DAY_PERIOD_TYPE_INDICATOR as DAY_PERIOD_TYPE_INDICATOR,
	GRI_RUN_ID as GRI_RUN_ID,
	MARGIN_GROUP as MARGIN_GROUP,
	MARKET_ID as MARKET_ID,
	MEMBER_COUNTERPARTY_ID as MEMBER_COUNTERPARTY_ID,
	TRADER_MNEMONIC as TRADER_MNEMONIC,
	ACCOUNT_TYPE as ACCOUNT_TYPE,
	CURRENCY_ID as CURRENCY_ID,
	BASE_CURRENCY_ID as BASE_CURRENCY_ID,
	FXRATE as FXRATE,
	IM as IM,
	IM_OPEN as IM_OPEN,
	IM_DELIVERY as IM_DELIVERY,
	VM as VM,
	CVM as CVM,
	NLV as NLV,
	ESA as ESA,
	CRIM as CRIM,
	IMM as IMM,
	DFAM as DFAM,
	IM_FX as IM_FX,
	CRIM_FX as CRIM_FX,
	IMM_FX as IMM_FX,
	PARTICIPANT_ROLE_TYPE as PARTICIPANT_ROLE_TYPE,
	POSITION_ACCOUNT_TYPE as POSITION_ACCOUNT_TYPE,
	CLIENT_IDENTIFIER as CLIENT_IDENTIFIER,
	CLIENT_IDENTIFIER_TYPE as CLIENT_IDENTIFIER_TYPE,
	IMM1 as IMM1,
	OUTRIGHT_RATES_IMMFP as OUTRIGHT_RATES_IMMFP,
	BASIS_IMMFP as BASIS_IMMFP,
	OPTIONS_LIQUIDITY_MARGIN as OPTIONS_LIQUIDITY_MARGIN,
	LCRM as LCRM,
	OPTIONS_VOLATILITY_ADJ as OPTIONS_VOLATILITY_ADJ,
	UNSCALED_VAR_ADDON as UNSCALED_VAR_ADDON,
	BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	ENTITY_ID as ENTITY_ID,
	NET_BH_TOTAL as NET_BH_TOTAL,
	CCY_HOL_VM as CCY_HOL_VM,
	CCY_HOL_VM_FX as CCY_HOL_VM_FX,
	OPTIONS_PREMIUM as OPTIONS_PREMIUM,
	ACTIVE_FLAG as ACTIVE_FLAG,
	ERROR_INDICATOR as ERROR_INDICATOR,
	PROPAGATE_INDICATOR as PROPAGATE_INDICATOR,
	FX_ADDON as FX_ADDON,
	FX_ADDON_FX as FX_ADDON_FX,
	MER as MER,
	SPMAddon as SPMAddon 
From dsJoiner_SC_RR_RATE_MARKET_MARGIN_FACT0Out as dsJoiner_SC_RR_RATE_MARKET_MARGIN_FACT0Out